# Generated by Django 4.1.7 on 2023-03-24 16:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Administrateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_profile', models.ImageField(blank=True, upload_to='images/')),
                ('titre', models.CharField(max_length=128)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'admin',
            },
        ),
        migrations.CreateModel(
            name='Etablissement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('libelle', models.CharField(max_length=128, unique=True)),
            ],
            options={
                'db_table': 'etablissement',
            },
        ),
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_profile', models.ImageField(blank=True, upload_to='images/')),
                ('no_carte', models.BigIntegerField(unique=True)),
                ('deposer', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'etudiant',
            },
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('libelle', models.CharField(max_length=128, unique=True)),
            ],
            options={
                'db_table': 'theme',
            },
        ),
        migrations.CreateModel(
            name='Parcours',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('libelle', models.CharField(max_length=128)),
                ('adminstrateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application_web_aky.administrateur')),
                ('etablissement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application_web_aky.etablissement')),
            ],
            options={
                'db_table': 'parcours',
            },
        ),
        migrations.CreateModel(
            name='Memoire',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('num_ordre', models.CharField(max_length=128)),
                ('titre', models.TextField()),
                ('description', models.TextField()),
                ('media', models.FileField(upload_to='documents/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('etudiant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='application_web_aky.etudiant')),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application_web_aky.theme')),
            ],
            options={
                'db_table': 'memoire',
                'ordering': ['created_at', 'num_ordre'],
            },
        ),
        migrations.AddField(
            model_name='etudiant',
            name='parcours',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application_web_aky.parcours'),
        ),
        migrations.AddField(
            model_name='etudiant',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
